### ISSUE TITLE
Dotaz od Štěpána Buřiče

### ISSUE THREAD

**Issue by RemakTeam** [ZhukovGreen/EC_Lot6_ComfTool#15]
Je to správně, že do výpočtu "The Minimum fan efficiency" vstupuje hodnota "dP_s_fan" z REFERENČNÍ jednotky a ne z Actual jednotky?

Snižuje to dosaženou účinnost ventilátoru, což jde na první pohled proti smyslu Ecodesignu

**Comment by ZhukovGreen** [comment]
It looks already ok

**Comment by ZhukovGreen** [comment]
@RemakTeam
