### ISSUE TITLE
optimizace dP na HRS

### ISSUE THREAD

**Issue by RemakTeam** [ZhukovGreen/EC_Lot6_ComfTool#8]
zvaž prosím, jestli přidat možnost hledání maximální přípustné tlakové ztráty na HRS.
Klukům a holkám z obchodu by to zjednodušilo život při hledání správné kostky

**Comment by ZhukovGreen** [comment]
I did optimization of dP for fan. Is it sufficient?
![capture](https://cloud.githubusercontent.com/assets/10520003/8391224/b31facf4-1cba-11e5-8aef-977cc988aa44.PNG)

**Comment by ZhukovGreen** [comment]
It seems for me it is solved by this capability:
![capture](https://cloud.githubusercontent.com/assets/10520003/9022598/f8397892-387b-11e5-8e91-faece14c91b4.PNG)
